spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        greetings-in:
          destination: spring-cloud-stream
          contentType: application/json
        greetings-out:
          destination: spring-cloud-stream
          contentType: application/json

#        input:
#          binder: kafka
#          destination: spring-cloud-stream
#          content-type: text/plain
#          group: input-group-1
#        output:
#          binder: kafka
#          destination: spring-cloud-stream
#          group: output-group-1
#          content-type: text/plain